### ISSUE TITLE
Privacy Provider Implementation 

### ISSUE THREAD

**Issue by aspark21** [ecampbell/moodle-booktool_wordimport#13]
Fatal error: Declaration of booktool_wordimport\privacy\provider::get_reason() must be compatible with core_privacy\local\metadata\null_provider::get_reason(): string in /var/www/html/mod/book/tool/wordimport/classes/privacy/provider.php on line 35

**Comment by ecampbell** [comment]
Hi Alaistair, can you tell me how you identify this error. It doesn't seem to arise when I use the Codechecker plugin, and I can't seem to get Travis to work at the moment.

**Comment by aspark21** [comment]
Hi Eoin,

This was from running the PHPUnit tests on our full build of Moodle.

Because it was fatal it crashed the run out before we get the report so I can't say for sure which test made it appear. I'm assuming it's one of the core ones.

Al

**Comment by ecampbell** [comment]
Thanks, do you need a public release on the Moodle plugins database, or is the Github update sufficient for the moment.

**Comment by aspark21** [comment]
For me github is fine :)
