### ISSUE TITLE
Error on export book to word.

### ISSUE THREAD

**Issue by neeesn** [ecampbell/moodle-booktool_wordimport#18]
Hi we get an error:

XSLT transformation failed

![image](https://user-images.githubusercontent.com/1931926/173532583-b1e584d2-2413-411c-8865-425879e3d3d1.png)

Our server has Xslt setup version 1.1.34: 
![image](https://user-images.githubusercontent.com/1931926/173532921-424acfab-d0b1-4798-9f78-a6101edffe88.png)

We have:
Moodle 3.11.6 (Build: 20220314)
Plugin version: 1.4.11 (Build: 2021083100)

We can export an chapter but not the whole book.

**Comment by ecampbell** [comment]
The most likely reason for this is malformed HTML in one or more chapters of the book. I suggest you edit and save each book chapter using the Atto editor, and then try exporting again. Atto does some HTML  clean-up which might resolve the problem.
