### ISSUE TITLE
word-2020

### ISSUE THREAD

**Issue by neeesn** [ecampbell/moodle-booktool_wordimport#19]
Is there an update, so it will be possible to export in word-2020 format?

**Comment by neeesn** [comment]
The newest wordformat

**Comment by ecampbell** [comment]
The plugin already supports exporting to Word 2020 format. There have been reports that a recent (July 2022) update to Word 365 causes images not to be opened properly by Word 365, but I haven't been able to reproduce this problem. If you have a book that does exhibit this problem, it would be useful if you could create a course backup file containing the resource and send it to me to investigate further. Another poster mentioned that it seems to arise only with PNG images.
