### ISSUE TITLE
Incorrect function name prefix in locallib.php

### ISSUE THREAD

**Issue by mudrd8mz** [ecampbell/moodle-booktool_wordimport#2]
Inspired by the locallib.php from the standard subplugin booktool_importhtml, you also use the prefix `toolbook_wordimport_` for your functions in your localllib.php.

Note that the standard plugin importhtml has this done wrong in the first place, the expected prefix should be the same as the frankenstyle component name of your plugin, that is `booktool_importhtml_*` and `booktool_wordimport_*`.

I can't really blame you for following the code contained with the standard Moodle distribution, ideally both places should be fixed eventually.

**Comment by mudrd8mz** [comment]
However, just spotted that in places like

    throw new moodle_exception('transformationfailed', 'toolbook_wordimport', $tempwordmlfilename);

the `toolbook_wordimport` is not correct component name and such an exception would not work well.

Additionally, the code

    'pluginname' => 'toolbook_wordimport'

in your `toolbook_wordimport_convert_to_xhtml()` uses invalid plugin name too. Not sure what consequences it may have.

**Comment by ecampbell** [comment]
All changed to booktool_wordimport
