### ISSUE TITLE
storedfilecannotread on import

### ISSUE THREAD

**Issue by leonstr** [ecampbell/moodle-booktool_wordimport#4]
When I click **Import from Microsoft Word** select a DOCX file and select **Import** I get the following error message with Moodle 3.3:

Debug info: /tempup_gXjpvu.zip
Error code: storedfilecannotread

Stack trace:
    line 350 of /lib/filestorage/file_system_filedir.php: file_exception thrown
    line 1766 of /lib/filestorage/file_storage.php: call to file_system_filedir->add_file_from_path()
    line 1321 of /lib/filestorage/file_storage.php: call to file_storage->add_file_to_pool()
    line 145 of /mod/book/tool/wordimport/locallib.php: call to file_storage->create_file_from_pathname()
    line 140 of /mod/book/tool/wordimport/index.php: call to booktool_wordimport_import_word()

**Comment by ecampbell** [comment]
Hi Leon,
Many thanks for fixing this bug for me.
