### ISSUE TITLE
Images in Book activity not exported/displayed when exported to Word.

### ISSUE THREAD

**Issue by jebarviabb** [ecampbell/moodle-booktool_wordimport#8]
Hi,

The images from Book activity are not exported to Word document.

I have used the following environments to test: Moodle (3.6dev+ build: 20181019) and Microsoft Word File Import/Export (Book) build 2018080601 at https://moodle.org/plugins/booktool_wordimport.
1. Create a course.
2. Turn editing on.
3. Add a new Book resource 
4. Give it a name and click on save and return to course. 
5. Click on the newly created Book resource and click on the toolbar toggle for the content editor. 
6. Click on the button for adding an image. 
7. Upload an image from your computer and insert it. It is useful to add more images. 
8. Add an image this time by typing in an external link rather than uploading from your computer. 
9. Submit changes 
10. Go to the bottom left and click on export to Microsoft Word 
11. You will find that the images that were uploaded from your computer will be converted to small red crosses but images from external link will work fine. 

Note: Even if you import a Word document and it displays fine on Moodle, if you export it to a Word document the images won't show.

**Comment by ecampbell** [comment]
The images are exported as Base64 data embedded in the Word file, and you have to run a VBA macro to convert them back into proper images. Unfortunately the VBA macro was declared a virus by Microsoft Windows Firewall, so I had to remove it from the Word template file for formatting books. You can download it from http://www.moodle2word.net/mod/resource/view.php?id=48.

Ideally, the Word file would be exported as a .docx file, avoiding this issue, but at the moment it is exported as a **HTML** file (but with a .doc suffix) containing special classes to format it nicely in Word.

**Comment by jebarviabb** [comment]
Thanks for that. So that explains why I can see a .doc file instead of a .docx and the .doc file is readable and I can see the XML code. Thanks and we will await once there is an integrated solution that would not require the VBA macro into converting them back into proper images on the fly. Thanks once again.

**Comment by ecampbell** [comment]
Unfortunately you may be waiting a while for a non-VBA solution. The way I envisage this tool working is that you maintain a master copy in Word, and import into Moodle. There is scope for a once-off export of a book from Moodle to Word to facilitate migration into Word for editing. So the VBA-based solution is not something that should be used on a regular basis.

**Comment by jebarviabb** [comment]
Thanks for the response. Now we have a better understanding of the plugin. Best regards.

**Comment by ecampbell** [comment]
Hi Joshua,
You may be interested to know that I have released a new version of the Word export for Book plugin that no longer relies on a VBA macro. Instead it generates a file containing embedded images that can be opened directly in Word 2020 or Word 365. These versions of Word handle images embedded in HTML very well, so it is a better approach than relying on VBA code.

**Comment by alexanderwilliams091** [comment]
Hi Eoin, 
This same issue appears to be occurring in v1.4.11 (2021083100) of the plugin. Exporting to file and opening the *.doc in Word on Mac at version 16.63.1 ((22071301); released July 15, 2022) is resulting in the same broken images. Had a colleague test this using a Windows 2022 released Word version and its similarly broken.
